[package]
name = "ordmask"
version = "1.0.0"
edition = "2021"
authors = ["Wzh <wzh@uvwee.com>"]
description = "To check if a value is included efficiently."
license = "MIT"
keywords = ["mask", "ordered", "range"]
repository = "https://github.com/wzh19960613/ordmask-rust"

[dependencies]
